load 'deploy' if respond_to?(:namespace) # cap2 differentiator

require 'rubygems'
require 'railsless-deploy'
require 'yaml'

load 'config/deploy' # remove this line to skip loading any of the default tasks
